Check Bash version

diff --git a/gh-token b/gh-token
--- a/gh-token
+++ b/gh-token
@@ -1,4 +1,10 @@
 #!/usr/bin/env bash
+
+if (( ${BASH_VERSION%%.*} < 5 )); then
+  echo "Bash is too old: ${BASH_VERSION}; Bash 5.+ is required"
+  exit 1
+fi
+
 ###############################################################################
 # * _____ _   *_   _______ *  _      *  *    **   *
 #  / ____| |* | | |__   __|  | |  *       *         🦄  *
